# This file contains alternate configurations to build a "developer" image variant.
# These configurations can be applied using the Yocto multiconfig feature:
# $ bitbake mc:<config>:<target>
#
# Example:
# $ bitbake mc:developer:pokytos-console-image
#

TMPDIR .= "-${BB_CURRENT_MC}"

# Custom recipes will look for a "developer" override to include or remove
# specific configurations for the developer image variant
MACHINEOVERRIDES:append = ":developer"

IMAGE_NAME_SUFFIX = "-developer.rootfs"
